### ISSUE TITLE
Husky and lint-staged dependencies

### ISSUE THREAD

**Issue by artursvonda** [SaraVieira/styled-flex-component#12]
Hi! We just started using your library and I see that husky and lint-staged have snuck in the dependencies list. They most likely should be in devDependencies.

I could do PR this week if nobody else does this first.

Thanks!

**Comment by SaraVieira** [comment]
Hey!

Yeah, that would be awesome!

Thank you

**Comment by druvisc** [comment]
https://github.com/SaraVieira/styled-flex-component/pull/13

**Comment by artursvonda** [comment]
@SaraVieira Did you have a chance to look a the PR?

**Comment by SaraVieira** [comment]
Hey!

Sorry for the delay, PR merged and the version `3.0.2` doesn't have the issue anymore :)
