### ISSUE TITLE
styled-components as peerDependencies 

### ISSUE THREAD

**Issue by gregStevenard** [SaraVieira/styled-flex-component#20]
Reason : when importing your package within a react project, it creates a new instance of `styled-components` when it should depends on the project's `styled-components`. No one should load several versions of `styled-components` within an app. It should be treated like react/react-dom. 

Suggestion is to add to the peerDependencies object :
`{'styled-components':'^5.1.0'} `

Please note that `styled-components@^5.1.1` would also be invalid as the last release is `5.1.0`. 

Hope this can happen :) Thanks @SaraVieira for the great work. It's a breeze to use. 

Edit : I bet most of the forks happened for this reason, causing their respective styles to break..

**Comment by SaraVieira** [comment]
Hey!

You are super right! Don't know how that slipped for so long.

Updated and published on version 3.0.3.

Thank you so much for pointing it out :)

I changed also the styled-components version but the weird thing is my computer always try to install 5.1.1 🤔

**Comment by gregStevenard** [comment]
@SaraVieira Woot! Thanks so much!  :) as for the 5.1.1, I bet we're just a few weeks away from that one anyway, not sure if that part is the most relevant! :)

**Comment by SaraVieira** [comment]
Just fixed a bug on this repo as well using the new shouldForwardProp so great release on my end 🎉
