### ISSUE TITLE
styled-components dependency

### ISSUE THREAD

**Issue by apihlaja** [SaraVieira/styled-flex-component#4]
FAQ suggests `styled-components` should be [peer dependency](https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library) (and dev dependency).

Current dependency causes easily dublicated `styled-components` which breaks in production mode. If I run `yarn add styled-components styled-flex-component` now, it installs silently dublicated copy:

```
yarn list --pattern styled-components
yarn list v1.3.2
├─ styled-components@3.1.6
└─ styled-flex-component@2.2.0
   └─ styled-components@3.1.4
```

**Comment by SaraVieira** [comment]
That makes perfect sense , I will change this now and make a new release

**Comment by SaraVieira** [comment]
Hello @apihlaja,
It should be fixed in https://github.com/SaraVieira/styled-flex-component/releases/tag/v2.2.1

Can you please reinstall and let me know ?

**Comment by apihlaja** [comment]
That works, it doesnt cause duplication anymore but I'd prefer peer dependency to be some version range ie. `"styled-components": "^3.1.4"` or at least `^3.1.4` to allow patch updates.

**Comment by SaraVieira** [comment]
Awesome !

You are right! It has been changed in https://github.com/SaraVieira/styled-flex-component/releases/tag/v2.2.2

Thank you for letting me know, I didn't know those things about creating styled-components libraries

**Comment by apihlaja** [comment]
All good now, thanks :+1:
