### ISSUE TITLE
Add row property

### ISSUE THREAD

**Issue by nmaves** [SaraVieira/styled-flex-component#5]
I know that the default behavior is to act like a row for a `Flex` component but I have a use case where I would like the default to be column but allow an override of row.

```
export const FieldGroup = Flex.extend.attrs({ column: true })`
  margin: 10px;
`
```

Then later I can use the following to override it.

```
<FieldGroup row></FieldGroup>
```

**Comment by artursvonda** [comment]
`<FieldGroup column={false}></FieldGroup>` perhaps?

**Comment by SaraVieira** [comment]
Hey!

What @artursvonda  said should work and I also added the row property to the docs in the Readme :)
