### ISSUE TITLE
FlexItem grow and shrink create incorrect styles

### ISSUE THREAD

**Issue by danyim** [SaraVieira/styled-flex-component#6]
`FlexItem`'s  grow and shrink attributes should produce `flex-grow: 1` and `flex-shrink: 1` respectively, but currently it produces `true` and `false` values.

https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow

**Comment by ramitos** [comment]
You can get `flex-grow: 1` and `flex-shrink: 1`:

```
<FlexItem grow={1} shrink={1} />
```
