### ISSUE TITLE
Setting 'wrap' prop leads to React warning

### ISSUE THREAD

**Issue by giylmi** [SaraVieira/styled-flex-component#9]
```Warning: Received 'true' for a non-boolean attribute 'wrap'.```

It looks like `wrap` prop is passed down since it is a valid html attribute. 
Maybe the prop should be renamed to be different from html attribute

**Comment by andrevst** [comment]
Does it works? Receiving the same warning here.

**Comment by andrevst** [comment]
It did, thanks

**Comment by Idan-Hen** [comment]
I also have this issue - can this be fixed any time soon ?

**Comment by SaraVieira** [comment]
Hey!

This was fixed now as styled-components just introduced the `shouldForwardProp` function that allows me to filter the props I wanna send down to the HTML and now the wrap prop is no longer sent 🎉

Fixed in 3.0.4
